POST http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"mail@mail.com",
    "password":"12345"
}


###




###
GET  http://localhost:4500/users/all
Content-Type: application/json


###

GET  http://localhost:4500/products
Content-Type: application/json


###
GET  http://localhost:4500/products/1fc7b941-0af0-4370-9ca9-1f629760
Content-Type: application/json


###
DELETE   http://localhost:4500/products/1fc7b941-0af0-4370-9ca9-1f6297606b66
Content-Type: application/json


###
PUT    http://localhost:4500/products/1d2e8de1-c707-405f-a0d3-bd235f11658b
Content-Type: application/json

{
    "productName": "Coffee",
    "description":"A cold cup of coffee",
    "category":"Tea",
    "stockQuantity":3,
    "regularPrice":245,
    "salePrice":235,
    "image": "http://res.cloudinary.com/dioueb86u/image/upload/v1709694697/Shopie%20Product%20Images/agwjzqwrc5sdelh0dr1q.jpg"
}


###

GET  http://localhost:4500/products
Content-Type: application/json


###


POST http://localhost:4500/cart
Content-Type: application/json

{
    "userId":"2e96b6aa-04cc-4c65-a37c-4955b6ed45",
    "productId":"54b5916d-10c6-45d6-b94c-4db1576451f0",
    "orderedQuantity": 4
}